"""Add password reset fields to users table

Revision ID: aecd7b3fa90d
Revises: e8c0bc300fe1
Create Date: 2026-01-16 14:06:36.103118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aecd7b3fa90d'
down_revision = 'e8c0bc300fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing password reset columns to users table if they don't exist
    try:
        op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    try:
        op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    try:
        op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    try:
        op.add_column('users', sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True))
    except Exception:
        pass  # Column might already exist
    
    # Create passkey tables (only if they don't exist)
    try:
        op.create_table('passkey_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('challenge', sa.String(length=255), nullable=False),
    sa.Column('challenge_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge')
    )
    except Exception:
        pass  # Table might already exist
    
    try:
        op.create_table('passkeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('aaguid', sa.String(length=36), nullable=True),
    sa.Column('transports', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_backup_eligible', sa.Boolean(), nullable=True),
    sa.Column('is_backup_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    except Exception:
        pass  # Table might already exist
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passkeys')
    op.drop_table('passkey_challenges')
    
    # Remove password reset columns if they exist
    try:
        op.drop_column('users', 'email_verification_sent_at')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'email_verification_token')
    except Exception:
        pass
    
    try:
        op.drop_column('users', 'password_reset_expires')
    except Exception:
        pass
        
    try:
        op.drop_column('users', 'password_reset_token')
    except Exception:
        pass
    # ### end Alembic commands ###
